name: CI/CD Pipeline for Next.js

# Kích hoạt workflow khi có push hoặc pull request vào nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Các job sẽ chạy trong workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Build ứng dụng Next.js
      - name: Build application
        run: npm run build

      # Bước 5: Chạy unit tests 
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Build ứng dụng Next.js
      - name: Build application
        run: npm run build

      # Bước 5: Deploy ứng dụng (Vercel)
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
